### ISSUE TITLE
Sugestão: Definir em local único os valores de timeout

### ISSUE THREAD

**Issue by Markenson** [crivano/swaggerservlet#1]
Reportado por Raphael Paiva (email er 14/06/2016 18:37), a sugestão de unificar o local que define os valores nas linhas abaixo (properties, talvez?)

https://github.com/crivano/swaggerservlet/blob/master/src/main/java/com/crivano/restservlet/RestUtils.java#L262
https://github.com/crivano/swaggerservlet/blob/master/src/main/java/com/crivano/restservlet/RestUtils.java#L281

**Comment by crivano** [comment]
@Markenson , você acabou resolvendo esse problema quando corrigiu a #1
